# Generated by Django 4.2 on 2023-05-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_customuser_phone_alter_customuser_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picturename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
