# Generated by Django 4.2 on 2023-05-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_blog_vlogpicturename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='username',
            field=models.TextField(),
        ),
    ]
